package com.wind.integration.metrics.dsl;

/**
 * 指标 DSL 基础结构错误码。
 */
public enum MetricDslErrorCode {

    DSL_JSON_INVALID,
    DSL_ROOT_NOT_OBJECT,
    DSL_FIELD_DUPLICATED,
    DSL_FIELD_UNKNOWN,
    DSL_FIELD_REQUIRED,
    DSL_FIELD_TYPE_INVALID,
    DSL_SCHEMA_VERSION_UNSUPPORTED,
    DSL_IDENTIFIER_INVALID,
    DSL_VALUE_BRANCH_INVALID,
    DSL_VALUE_INVALID,
    DSL_PLAN_INVALID,
    QUERY_INVALID,
    RESULT_INVALID
}
